version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: messenger
      POSTGRES_PASSWORD: password
  server:
    build:
      context: ..
      dockerfile: deployments/server/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:50051:50051
      - 127.0.0.1:9092:9092
    links:
      - db:db
    environment:
      PROMETHEUS_ADDR: 0.0.0.0:9092
      GRPC_ADDR: 0.0.0.0:50051
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: messenger
      DB_PASSWORD: password
    depends_on:
      - db
  # client:
  #   build:
  #     context: ..
  #     dockerfile: deployments/client/Dockerfile
  #   restart: always
  #   network_mode: host
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - server

