version: "3.7"


services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: drag
      POSTGRES_DB: messenger
      POSTGRES_PASSWORD: terra5308
  server:
    build:
      context: ..
      dockerfile: deployments/server/Dockerfile
    restart: always
    environment:
      GRPC_HOST: localhost
      GRPC_PORT: 50051
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: drag
      DB_NAME: messenger
      DB_PASSWORD: terra5308
    network_mode: host
    ports:
      - 50051:50051
    depends_on:
      - db
  # client:
  #   build:
  #     context: ..
  #     dockerfile: deployments/client/Dockerfile
  #   restart: always
  #   network_mode: host
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - server

