global:
  scrape_interval: 20s
  scrape_timeout: 15s

  external_labels:
    monitor: 'messenger-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grpc-server'
    static_configs:
      - targets: ['localhost:9092']

  # - job_name: 'grpc-client-1'
  #   static_configs:
  #     - targets: ['localhost:9094']
